### ISSUE TITLE
Message appearing when closing any file

### ISSUE THREAD

**Issue by MtbGot** [GiuseppeDotto/pyM4B.extension#2]
Hello, 
Everytime I close a file, the following message appears:
Thank you!!!

IronPython Traceback:
Traceback (most recent call last):
 File "C:\Users\Usuario\AppData\Roaming\pyRevit\Extensions\PyM4B.extension\hooks\doc-closing.py", line 30, in <module>
ValueError: substring [ not found in Jrn.Activate "" , "Sheet: - "

Script Executor Traceback:
IronPython.Runtime.Exceptions.ValueErrorException: substring [ not found in Jrn.Activate "" , "Sheet: - "

 at lambda_method(Closure , Object[] , StrongBox`1[] , InterpretedFrame )
 at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
 at IronPython.Compiler.PythonScriptCode.RunWorker(CodeContext ctx)
 at PyRevitLabs.PyRevit.Runtime.IronPythonEngine.Execute(ScriptRuntime& runtime)

**Comment by GiuseppeDotto** [comment]
Solved. Now the script deals also with unnamed files.
The issue was caused by the attempt to get the project name between "[ ]", which is how commonly appears in journal files. Now it is using the " character.
